### ISSUE TITLE
Add Me

### ISSUE THREAD

**Issue by dawnsl2020** [Cambridge-Digital-Library/Crowdsourcing#163]
Hello,
I'm sorry, I'm new to this and when I sent the message before I didn't realise that I could add my credentials here. I am a graduate in Botany from the University of Bristol and I am an ecologist running my own small consultancy with my partner (Wessex Ecological Consultancy). Although I am not always up to date with the latest name changes I am confident that I will recognise all the common and scientific names used by Oliver Rackham and will therefore be well-placed to transcribe his notebooks. I have long been an admirer, owning several of his books. I was lucky enough to meet him once, when he visited Winterbourne near Bristol where he was good friends with the vicar. He led a guided walk and he signed my copy of History of the British Countryside. I come from Bedfordshire and am familiar with Hayley Wood, Gamlingay Wood and several others that he studied though I now live in Bristol. 
My email address is dawn@wessexeco.co.uk.
I would love to help to transcribe his notebooks. Please let me know if you need any more information from me. 
I look forward to hearing from you soon.
Best regards,
Dawn Lawrence

**Comment by Cambridge-Digital-Library** [comment]
Hi Dawn,
Thanks for joining the project!

No need for credentials, its just I haven't had chance to check here over the weekend and I need to manually add you before you can edit, the project is open to everyone - although you sound perfectly qualified, so it's good to know there's someone who might be able to help out if anyone comes up against any tricky bits!

I've done this now, so you should have received an "invitation to collaborate" from Github, once you accept that you will be able to continue with the next steps.

I hope you enjoy getting started, do let us know if you have any questions or need any help.
All the best,
Andy
Cambridge Digital Library

**Comment by dawnsl2020** [comment]
Hello,
Thank you, I am looking forward to it. If I have a question, do I put it on here for you? Or is email better?
Cheers,
Dawn

**Comment by Cambridge-Digital-Library** [comment]
Hi @dawnsl2020, 

You can either comment on the specific notebook task as you have done for Notebook 229 (particularly where it's something specific to the notebook in question), or if you have more general  questions then you could either ask here or go to the "Issues" list and create a new "Issue":
https://github.com/Cambridge-Digital-Library/Crowdsourcing/issues

I'll probably notice either, but to be double sure, you can also use "@Cambridge-Digital-Library" (a bit like Twitter) to tag and notify me as I've done above.

I'll have a look at your questions over on the notebook task shortly.
All the best,
Andy
