### ISSUE TITLE
Create Guide: Create Account & Join

### ISSUE THREAD

**Issue by Cambridge-Digital-Library** [Cambridge-Digital-Library/Crowdsourcing#7]
Create Guide page for creating a GitHub account, joining the project and uploading your transcription file.

**Comment by IrisBox** [comment]
Started here:
https://github.com/Cambridge-Digital-Library/Crowdsourcing/blob/master/_posts/account-set-up.md

**Comment by Cambridge-Digital-Library** [comment]
Looking good!
Huw

**Comment by IrisBox** [comment]
This is done:
https://github.com/Cambridge-Digital-Library/Crowdsourcing/blob/master/docs/get-started.html
